### ISSUE TITLE
Does not work on macOS without change to shebang line in chatgpt.py

### ISSUE THREAD

**Issue by wbpayne22902** [marcolardera/chatgpt-cli#12]
On systems running macOS, this runs fine after the shebang line is changed.  In macOS the correct shebang would be `#!/usr/bin/env python3`.  After this change chatgpt-cli works perfectly.

**Comment by marcolardera** [comment]
Shebangs are very system dependent and there is no way to include multiple of them. The standard way to run the script, however, should always be `python chatgpt.py` (or any alias of that).
