### ISSUE TITLE
don't rely on WORKDIR to run

### ISSUE THREAD

**Issue by dst78** [marcolardera/chatgpt-cli#30]
The program won't find its config file (and I assume also the .history file) if it is being executed from anywhere other than the directory where the .py file itself is.

It would be much more convenient if those files would be written to ~/.config/chatgpt-cli or any other known directory so that the program can be executed from anywhere, for example through an alias.

Alternatively or on top of that, you could add a config parameter to supply that path. This would enable use of multiple ChatGPT accounts.

**Comment by marcolardera** [comment]
This is solved.
