### ISSUE TITLE
Cope more gracefully with "Unknown error, status code 502"

### ISSUE THREAD

**Issue by mk-pmb** [marcolardera/chatgpt-cli#39]
First the service was overloaded, so I retried, and it worked for one question, then 502.

> During handling of the above exception, another exception occurred: … requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The only relevant trace step was

> File "./chatgpt.py", line 227, in start_prompt    console.print(r.json())

Is this HTTP? Then 502 would mean Bad Gateway, which I often observed with nginx as load balancer when the downstream server was too busy to reply at all.

**Comment by marcolardera** [comment]
All errors other then then 400, 401 and 429 are classified as "Unknown error" and that triggers an EOFError that closes the application.

In case of 502 what do you think is the best behaviour?  If this usually means a temporary server error, probably the best way to handle is to continue the loop (asking the user prompt again) instead of breaking...

**Comment by mk-pmb** [comment]
> In case of 502 what do you think is the best behaviour?

Part 1, help users understand what 502 means.

> If this usually means a temporary server error,

Displaying this description would be a good start.

> probably the best way to handle is […] asking the user prompt again

Then we should also display this recommendation, and give users an easy way to do it. When we're in an input mode where the prompt can be re-edited by just pressing the up key, we should remind users about that approach. In dumb prompts, we should offer something like "Enter /resend to try again asking the same question."

**Comment by marcolardera** [comment]
Done with https://github.com/marcolardera/chatgpt-cli/commit/7d9628d3e863e9c183200a18109bff42b472f4e6

**Comment by mk-pmb** [comment]
Thanks! While https://github.com/marcolardera/chatgpt-cli/commit/7d9628d3e863e9c183200a18109bff42b472f4e6 explains the error type good enough, it seems to not address the advice part about how to retry easily. Is that part out of scope for this project?

**Comment by marcolardera** [comment]
Retry means just pressing up-key + enter. I think it's obvious enough to not need additional explanations (it's standard in almost all REPL environments)...
