### ISSUE TITLE
GPT Models are not applied correctly

### ISSUE THREAD

**Issue by nilsujma-dev** [marcolardera/chatgpt-cli#41]
Command : chatgpt-cli --model gpt-4-0613 
ChatGPT CLI
Model in use: gpt-4-0613
[0] >>> Which GPT model are you
I'm based on OpenAI's GPT-3 model.                                                                                                                                                                                    
[53] >>>

Directly in ChatGPT with Model 4:

Which GPT model/version are you?
ChatGPT
I am based on the GPT-4 architecture. 
My training data includes information up to September 2021. If you have any questions or need assistance, feel free to ask!

**Comment by marcolardera** [comment]
Seems fine... You are using GPT4 and he told you so. What I'm missing?
