### ISSUE TITLE
feature request: in-shell interface

### ISSUE THREAD

**Issue by kirilligum** [marcolardera/chatgpt-cli#42]
something like:
```
chatgpt-cli -t "how do i install chatgpt-cli on ubuntu"
```

instead getting into repl

it would really help with scripting

**Comment by marcolardera** [comment]
Thanks for the idea, I like it :)

**Comment by moxious** [comment]
@kirilligum I implemented this recently via this PR, I think this is done

https://github.com/marcolardera/chatgpt-cli/pull/44

**Comment by marcolardera** [comment]
Yes, exactly, this is done with the piping commit.
