### ISSUE TITLE
default character encoding in some machines with Win OS causes crash!

### ISSUE THREAD

**Issue by orsnaro** [marcolardera/chatgpt-cli#57]
***[PR#58](https://github.com/marcolardera/chatgpt-cli/pull/58)***
---
The bug is actually easy to fix but causes the whole code to collapse. 

<details>
<summary> Details </summary>
file i/o `open()` function have `encoding` argument that by default is set to the machine's default character encoding. 

* Most Linux machines uses `utf-8` as default encoding which is ok with most languages characters, emojis and symbols.

* In Windows machines, a big portion of them uses [`cp1252`](https://en.wikipedia.org/wiki/Windows-1252) as default encoding which is **very** limited:
![get win default encoding via python script](https://github.com/marcolardera/chatgpt-cli/assets/77698890/a9ad943c-bd29-4946-b5ae-95f94cc990e5)
<sub>(as you see even if user didn't send any invalid characters, GPT sending one invalid character is enough to cause the bug)</sub>

---
> *open() docs: "if encoding is not specified the encoding used is platform **dependent**" [see](https://docs.python.org/3.5/library/functions.html#open)*

</details>

* ***Reproducing the bug***
![bug screenshot using Cmder shell & win terminal preview](https://github.com/marcolardera/chatgpt-cli/assets/77698890/6bbf5eba-8d38-46a6-b138-e6078153efd5)

* ***Fix*** 
simply assigning `open( , encoding= "utf-8")` for all systems or detecting the system encoding first using:
```py
import locale
sys_char_encoding = locale.getpreferredencoding())
#rest of the code
```

**Comment by marcolardera** [comment]
Thank you @orsnaro for catching this bug affecting Windows machines, I merged your fix...
