### ISSUE TITLE
Model in use gpt-4 or gpt-3?

### ISSUE THREAD

**Issue by giacman** [marcolardera/chatgpt-cli#72]
<img width="518" alt="image" src="https://github.com/marcolardera/chatgpt-cli/assets/7481763/87cf6316-13b5-483d-a6f5-e4aca49cb0b3">

Hi I have noticed this strange behaviour as I was using the CLI. Chat started to give me old code recommendations, so I asked what model I was interacting with and it said gpt-3 even though I specified to use gpt-4 and this was also confirmed by the CLI interface when I launched the script. 

I'm not sure if this is an issue or if I am missing something..

Thanks!

**Comment by marcolardera** [comment]
This is not an issue. You are using gpt-4. He's just hallucinating...

**Comment by mkulinyu** [comment]
I have the same problem, he is hallucinating pretty hard. I have to keep convincing it that it knows info past 2021 for some reason. GPT-4o is the only one that realizes it has information upto 2023. Anythign I can do to correct the behavior with 4 and 4-turbo ?
