### ISSUE TITLE
OpenAI chatgpt 156 chars api-key compatibility?

### ISSUE THREAD

**Issue by Gigithecode** [marcolardera/chatgpt-cli#77]
Hello,
Since openai change to 156 chars long their so-called secret key, chatgpt-cli doesn't seem to work.
"Invalid API Key"

**Comment by marcolardera** [comment]
Hi @Gigithecode , I'm using 156 char api keys without problems. There are no length check for the key.

The error "Invalid API Key" is a 401 status code, meaning that the provided key is invalid. Can you try with a new key or check if the one you are using is correct?

**Comment by Gigithecode** [comment]
Hello, I tries with three new keys... no success.
The config.yaml is as follow :
# Supplier: openai, azure
supplier: "openai"

# If supplier is OpenAI, please set this value
api-key: "my 156 key here"
model: "gpt-3.5-turbo"

# If supplier is Azure, please set this value
azure_endpoint: "https://xxxx.openai.azure.com/"
azure_api_version: "2023-07-01-preview"
azure_api_key: "<INSERT YOUR AZURE API KEY HERE>"
azure_deployment_name: "gpt-35-turbo"
azure_deployment_name_eb: "text-embedding-ada-002"

# Settings
temperature: 1
#max_tokens: 500 
markdown: true
easy_copy: true

# proxy setting
use_proxy: false
proxy: "socks5://127.0.0.1:2080" # supports http socks4 socks5
--------------------------
(venv3) gigi@gigi-Sky-X4E2G:~/chatgpt-cli$ ./src/chatgpt.py 
ChatGPT CLI                                                                                                                
Supplier: openai                                                                                                           
Model in use: gpt-3.5-turbo                                                                                                
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[0] >>> hi
Invalid API Key                                                                                                            
                                                                                                                           
Total tokens used: 0                                                                                                       
Estimated expense: $0.000000     
----------------------
I've $5 on my account.

**Comment by marcolardera** [comment]
Is possible that you have also set the OPENAI_API_KEY environment variable to an invalid key?

The priority order is:

command line argument > env variable > config file

In this case it would overwrite your config.yaml config.

**Comment by Gigithecode** [comment]
Would be great to verify if something is wrong reading a long key from config.yaml (ok from OPENAI_API_KEY)
